no_feature_selection_header = [
    "@relation botiot\n",
    "@attribute 'pkseqid' numeric\n",
    "@attribute 'stime' numeric\n",
    # flgs
    "@attribute 'e*' numeric\n",
    "@attribute 'e' numeric\n",
    "@attribute 'eF' numeric\n",
    "@attribute 'es' numeric\n",
    "@attribute 'eU' numeric\n",
    "@attribute 'eg' numeric\n",
    "@attribute 'e&' numeric\n",
    "@attribute 'ed' numeric\n",
    "@attribute 'er' numeric\n",
    # proto
    "@attribute 'icmp' numeric\n",
    "@attribute 'igmp' numeric\n",
    "@attribute 'udp' numeric\n",
    "@attribute 'arp' numeric\n",
    "@attribute 'tcp' numeric\n",
    "@attribute 'ipv6-icmp' numeric\n",
    "@attribute 'rarp' numeric\n",
    #
    "@attribute 'sport' numeric\n",
    "@attribute 'dport' numeric\n",
    "@attribute 'pkts' numeric\n",
    "@attribute 'bytes' numeric\n",
    # state
    "@attribute 'RSP' numeric\n",
    "@attribute 'CON' numeric\n",
    "@attribute 'FIN' numeric\n",
    "@attribute 'REQ' numeric\n",
    "@attribute 'ACC' numeric\n",
    "@attribute 'NRS' numeric\n",
    "@attribute 'URP' numeric\n",
    "@attribute 'RST' numeric\n",
    "@attribute 'INT' numeric\n",
    #
    "@attribute 'ltime' numeric\n",
    "@attribute 'seq' numeric\n",
    "@attribute 'dur' numeric\n",
    "@attribute 'mean' numeric\n",
    "@attribute 'stddev' numeric\n",
    "@attribute 'sum' numeric\n",
    "@attribute 'min' numeric\n",
    "@attribute 'max' numeric\n",
    "@attribute 'spkts' numeric\n",
    "@attribute 'dpkts' numeric\n",
    "@attribute 'sbytes' numeric\n",
    "@attribute 'dbytes' numeric\n",
    "@attribute 'rate' numeric\n",
    "@attribute 'srate' numeric\n",
    "@attribute 'drate' numeric\n",
    "@attribute 'sipv4_pos1' numeric\n",
    "@attribute 'sipv4_pos2' numeric\n",
    "@attribute 'sipv4_pos3' numeric\n",
    "@attribute 'sipv4_pos4' numeric\n",
    "@attribute 'sipv6_pos1' numeric\n",
    "@attribute 'sipv6_pos2' numeric\n",
    "@attribute 'sipv6_pos3' numeric\n",
    "@attribute 'sipv6_pos4' numeric\n",
    "@attribute 'sipv6_pos5' numeric\n",
    "@attribute 'sipv6_pos6' numeric\n",
    "@attribute 'sipv6_pos7' numeric\n",
    "@attribute 'sipv6_pos8' numeric\n",
    "@attribute 'dipv4_pos1' numeric\n",
    "@attribute 'dipv4_pos2' numeric\n",
    "@attribute 'dipv4_pos3' numeric\n",
    "@attribute 'dipv4_pos4' numeric\n",
    "@attribute 'dipv6_pos1' numeric\n",
    "@attribute 'dipv6_pos2' numeric\n",
    "@attribute 'dipv6_pos3' numeric\n",
    "@attribute 'dipv6_pos4' numeric\n",
    "@attribute 'dipv6_pos5' numeric\n",
    "@attribute 'dipv6_pos6' numeric\n",
    "@attribute 'dipv6_pos7' numeric\n",
    "@attribute 'dipv6_pos8' numeric\n",
    "@attribute 'attack' {normal, attack}\n",
    "@data\n",
]


balanced_feature_selection_header = [
    "@relation botiot\n",
    "@attribute 'sipv4_pos4' numeric\n",
    "@attribute 'CON' numeric\n",
    "@attribute 'attack' {normal, attack}\n",
    "@data\n",
]


unbalanced_feature_selection_header = [
    "@relation botiot\n",
    "@attribute 'CON' numeric\n",
    "@attribute 'attack' {normal, attack}\n",
    "@data\n",
]
